version : '3'
services :
  app :
    build :
      context : .
      dockerfile : ./docker/php.dockerfile
    restart : always
    tty : true
    ports :
      - '80:80'
    volumes :
      - .:/var/www/html:delegated
    depends_on :
      - mysql
    networks :
      - internet
      - no-internet

  mysql :
    image : 'mysql:8.0'
    restart : always
    ports :
      - '127.0.0.1:3306:3306'
    environment :
      MYSQL_ROOT_PASSWORD : '${DB_PASSWORD}'
      MYSQL_DATABASE : '${DB_DATABASE}'
      MYSQL_USER : '${DB_USERNAME}'
      MYSQL_PASSWORD : '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    volumes :
      - mysql:/var/lib/mysql
    networks :
      - no-internet
    healthcheck :
      test : [ "CMD", "mysqladmin", "ping" ]

networks :
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes :
  mysql :
    driver : local
